spring:
  application:
    name: basic-security-v2
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: avCowJdnr6vGSMChndkD
            client-secret: i99wAdqTLW
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - name
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.basicsecurityv2.model

jwt:
  issuer: yjincode@naver.com
  secret_key: TxtJis9h77eIpfHsfMdvUqivAE58iDFgMkCnGZL/BlADgUzv1gfox6224u4Rwg+7VhwNeolG5PJiN3vggm1Pzw==